repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: requirements-txt-fixer
      - id: mixed-line-ending
      - id: check-toml

  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
      - id: black-jupyter

  - repo: https://github.com/kynan/nbstripout
    rev: 0.6.1
    hooks:
      - id: nbstripout

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.1
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier
          - "prettier-plugin-toml"

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.24.1
    hooks:
      - id: check-github-workflows
      - id: check-readthedocs

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.0
    hooks:
      - id: mypy
        additional_dependencies: [numpy, PyQt5-stubs, types-requests]
        args:
          [
            --ignore-missing-imports,
            --disallow-untyped-defs,
            --warn-redundant-casts,
          ]

  - repo: https://github.com/asottile/reorder-python-imports
    rev: v3.10.0
    hooks:
      - id: reorder-python-imports

  - repo: https://github.com/pycqa/flake8
    rev: "6.1.0"
    hooks:
      - id: flake8
        args:
          - "--max-line-length=88"
          - "--ignore=E501,W503,E203"

  - repo: https://github.com/rhysd/actionlint
    rev: "v1.6.25"
    hooks:
      - id: actionlint

ci:
  autoupdate_schedule: quarterly
