name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci-pip:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["windows-latest"]
        python-version: ["3.7", "3.8", "3.9"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Mesa 3D to get OpenGL support on windows without a GPU
        uses: ssciwr/setup-mesa-dist-win@v1
      - run: pip install -e .[tests] --verbose
      - run: pytest -k test_display_results
      - run: python -m pytest --cov=motor_task_prototype --cov-report=xml -v -s --log-cli-level=DEBUG
      - uses: actions/upload-artifact@v3
        with:
          path: ./*.png
      - uses: codecov/codecov-action@v3
        with:
          files: ./coverage.xml
          name: ${{ matrix.os }}-${{ matrix.python-version }}
          fail_ci_if_error: true
          verbose: true
