name: NSIS Windows Installer

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  pypi:
    name: Create and upload windows installer
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - run: makensis.exe /V4 vstt-windows-installer.nsi
      - uses: svenstaro/upload-release-action@v2
        if: github.ref == 'refs/heads/main'
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: vstt-windows-installer.exe
          tag: latest
          overwrite: true
          file_glob: true
          prerelease: true
