name: Wheel

on:
  push:
    branches:
      - main
    tags:
      - "*.*.*"
jobs:
  pypi:
    name: Upload wheel to github "latest" release
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - run: pip install --upgrade build
      - run: python -m build
      - run: mv dist/vstt-*-py3-none-any.whl vstt-latest-py3-none-any.whl
      - uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: vstt-latest-py3-none-any.whl
          tag: latest
          overwrite: true
          file_glob: true
          prerelease: true
